name: App service Build and Deploy Python package to Azure Web App
on: push

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master
    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Run pip
      shell: bash
      run: |
        pushd .
        python -m pip install --upgrade pip
        pip install -numpy==1.18.0
        pip install scipy==1.2.3
        pip install -r requirements.txt --target=".python_packages/lib/python3.8.2/site-packages"
        popd

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: jared-equity-visualization
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
